version: "3"
services:
  db:
    image: postgres:13
    ports:
      - "54321:5432"
    restart: always
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD