micronaut:
  application:
    name: kadai20200329
datasources:
  default:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
flyway:
  datasources:
    default:
      enabled: true
